### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by JoshCartledge** [robhammond/home-analytics#1]
Hi Rob

As discussed on email please see output below:

josh@raspberrypi:~ $ pm2 stop 0
[PM2] Spawning PM2 daemon with pm2_home=/home/josh/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Applying action stopProcessId on app [0](ids: [ '0' ])
[PM2][ERROR] Process 0 not found
josh@raspberrypi:~ $ npm run dev
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/josh/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/josh/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/josh/.npm/_logs/2023-03-07T21_12_22_150Z-debug-0.log

Log details below:

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.5.0
2 info using node@v18.14.2
3 timing npm:load:whichnode Completed in 5ms
4 timing config:load:defaults Completed in 11ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 9ms
6 timing config:load:builtin Completed in 10ms
7 timing config:load:cli Completed in 9ms
8 timing config:load:env Completed in 2ms
9 timing config:load:project Completed in 5ms
10 timing config:load:file:/home/josh/.npmrc Completed in 0ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 2ms
14 timing config:load:setEnvs Completed in 6ms
15 timing config:load Completed in 53ms
16 timing npm:load:configload Completed in 54ms
17 timing npm:load:mkdirpcache Completed in 2ms
18 timing npm:load:mkdirplogs Completed in 3ms
19 verbose title npm run dev
20 verbose argv "run" "dev"
21 timing npm:load:setTitle Completed in 9ms
22 timing config:load:flatten Completed in 18ms
23 timing npm:load:display Completed in 24ms
24 verbose logfile logs-max:10 dir:/home/josh/.npm/_logs/2023-03-07T21_12_22_150Z-
25 verbose logfile /home/josh/.npm/_logs/2023-03-07T21_12_22_150Z-debug-0.log
26 timing npm:load:logFile Completed in 33ms
27 timing npm:load:timers Completed in 1ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 136ms
30 silly logfile done cleaning log files
31 timing command:run Completed in 18ms
32 verbose stack Error: ENOENT: no such file or directory, open '/home/josh/package.json'
33 verbose cwd /home/josh
34 verbose Linux 5.15.84-v8+
35 verbose node v18.14.2
36 verbose npm  v9.5.0
37 error code ENOENT
38 error syscall open
39 error path /home/josh/package.json
40 error errno -2
41 error enoent ENOENT: no such file or directory, open '/home/josh/package.json'
42 error enoent This is related to npm not being able to find a file.
42 error enoent
43 verbose exit -2
44 timing npm Completed in 262ms
45 verbose code -2
46 error A complete log of this run can be found in:
46 error     /home/josh/.npm/_logs/2023-03-07T21_12_22_150Z-debug-0.log

**Comment by robhammond** [comment]
Hi Josh,

It looks like the issue is which directory you've cloned the repository to - the readme suggests `/var/www/home-analytics` so I'll assume it's installed there.

So if you do `cd /var/www/home-analytics` then `npm run dev` what is the output?
