### ISSUE TITLE
Site can’t be reached

### ISSUE THREAD

**Issue by oxhey** [robhammond/home-analytics#2]
I have followed the instructions in the medium post. 

I get to step 5 , run the command and access the dashboard from the browser. However when I try and go to any of the other pages such as admin, I get the err connection refused page in the browser. This seems to break everything as I am unable to return back to the dashboard

**Comment by robhammond** [comment]
Hi, thanks for raising the issue; are you able to post the output of the server logs to debug further?

If you're running the pm2 server you can find this by running `pm2 list` on the command line, then using the ID of the process (in the example below it is zero), run something like:

```sh
pm2 logs 0 --lines 150
```

**Comment by oxhey** [comment]
Here are the logs.

`[TAILING] Tailing last 150 lines for [0] process (change the value with --lines option)
/home/energymon/.pm2/logs/--npm-run-dev-error.log last 150 lines:
0|; npm ru | node:internal/process/promises:288
0|; npm ru |             triggerUncaughtException(err, true /* fromPromise */);
0|; npm ru |             ^
0|; npm ru | 
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | 
0|; npm ru | Node.js v18.16.0
0|; npm ru | node:internal/process/promises:288
0|; npm ru |             triggerUncaughtException(err, true /* fromPromise */);
0|; npm ru |             ^
0|; npm ru | 
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | 
0|; npm ru | Node.js v18.16.0
0|; npm ru | node:internal/process/promises:288
0|; npm ru |             triggerUncaughtException(err, true /* fromPromise */);
0|; npm ru |             ^
0|; npm ru | 
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | 
0|; npm ru | Node.js v18.16.0

/home/energymon/.pm2/logs/--npm-run-dev-out.log last 150 lines:
0|; npm ru | 
0|; npm ru |    7 router.get("/", async (req, res) => {
0|; npm ru |    8     try {
0|; npm ru |    9         let setupStatus = { tariff: false, consumption: false, vehicle: false };
0|; npm ru | → 10         const supplierSetup = await prisma.supplier.findFirst(
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async t._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async t._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/index.js:10:31 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET / 200 324.034 ms - 7284
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.supplier.findFirst()` invocation in
0|; npm ru | /var/www/home-analytics/app/web/routes/index.js:10:53
0|; npm ru | 
0|; npm ru |    7 router.get("/", async (req, res) => {
0|; npm ru |    8     try {
0|; npm ru |    9         let setupStatus = { tariff: false, consumption: false, vehicle: false };
0|; npm ru | → 10         const supplierSetup = await prisma.supplier.findFirst(
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async t._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async t._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/index.js:10:31 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET / 200 53.064 ms - 7284
0|; npm ru | GET /css/main.css 200 231.354 ms - 1271
0|; npm ru | GET /fontawesome/css/brands.css 200 193.808 ms - 23682
0|; npm ru | GET /fontawesome/css/solid.css 200 181.821 ms - 625
0|; npm ru | GET /fontawesome/css/fontawesome.css 200 244.601 ms - 113177
0|; npm ru | GET /js/charts.js 200 184.184 ms - 14337
0|; npm ru | GET /js/tables.js 200 149.877 ms - 4152
0|; npm ru | GET /js/heating.js 200 68.822 ms - 2995
0|; npm ru | GET /js/main.js 200 45.060 ms - 2
0|; npm ru | GET /fontawesome/webfonts/fa-solid-900.woff2 200 39.214 ms - 150472
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET /api/usage/hourly/compare?date1=2023-06-05&date2=2023-06-06&unit=halfhour&_=1686067094983 500 49.208 ms - 21
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET /api/usage/breakdown?start=2023-05-29&end=2023-06-05&_=1686067094984 500 140.283 ms - 21
0|; npm ru | [nodemon] app crashed - waiting for file changes before starting...
0|; npm ru | 
0|; npm ru | > home_analytics@1.0.0 dev
0|; npm ru | > nodemon -e js,mjs,json,ejs ./bin/www
0|; npm ru | 
0|; npm ru | [nodemon] 2.0.20
0|; npm ru | [nodemon] to restart at any time, enter `rs`
0|; npm ru | [nodemon] watching path(s): *.*
0|; npm ru | [nodemon] watching extensions: js,mjs,json,ejs
0|; npm ru | [nodemon] starting `node ./bin/www`
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.supplier.findFirst()` invocation in
0|; npm ru | /var/www/home-analytics/app/web/routes/index.js:10:53
0|; npm ru | 
0|; npm ru |    7 router.get("/", async (req, res) => {
0|; npm ru |    8     try {
0|; npm ru |    9         let setupStatus = { tariff: false, consumption: false, vehicle: false };
0|; npm ru | → 10         const supplierSetup = await prisma.supplier.findFirst(
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async t._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async t._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/index.js:10:31 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET / 200 290.907 ms - 7284
0|; npm ru | GET /css/main.css 304 18.392 ms - -
0|; npm ru | GET /fontawesome/css/fontawesome.css 304 140.228 ms - -
0|; npm ru | GET /fontawesome/css/brands.css 304 119.592 ms - -
0|; npm ru | GET /fontawesome/css/solid.css 304 110.259 ms - -
0|; npm ru | GET /js/charts.js 304 103.018 ms - -
0|; npm ru | GET /js/tables.js 304 90.425 ms - -
0|; npm ru | GET /js/heating.js 304 89.532 ms - -
0|; npm ru | GET /js/main.js 304 9.052 ms - -
0|; npm ru | GET /fontawesome/webfonts/fa-solid-900.woff2 304 17.227 ms - -
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET /api/usage/hourly/compare?date1=2023-06-05&date2=2023-06-06&unit=halfhour&_=1686067744643 500 41.368 ms - 21
0|; npm ru | PrismaClientInitializationError: 
0|; npm ru | Invalid `prisma.$queryRaw()` invocation:
0|; npm ru | 
0|; npm ru | 
0|; npm ru | Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
0|; npm ru |     at fn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6750)
0|; npm ru |     at fn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:5907)
0|; npm ru |     at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3087
0|; npm ru |     at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3294
0|; npm ru |     at async Proxy._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10748)
0|; npm ru |     at async Proxy._request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:10477)
0|; npm ru |     at async /var/www/home-analytics/app/web/routes/api.js:500:29 {
0|; npm ru |   clientVersion: '4.12.0',
0|; npm ru |   errorCode: undefined
0|; npm ru | }
0|; npm ru | GET /api/usage/breakdown?start=2023-05-29&end=2023-06-05&_=1686067744644 500 38.809 ms - 21
0|; npm ru | [nodemon] app crashed - waiting for file changes before starting...
`

**Comment by oxhey** [comment]
I dont see anything.

It just goes to a new line in the terminal

**Comment by robhammond** [comment]
Ah ok sorry about that - looks like that environment variable needs to be set. The app needs it to find the SQLite database file - try the following to set it:

```sh
echo "export HA_DB_URL=/var/www/home-analytics/app/db/prod.db" >> ~/.bashrc
source ~/.bashrc
```

Then restart your shell and run:

```sh
pm2 reload 0
```

**Comment by oxhey** [comment]
Just did a fresh install.

Same issue in the logs - Error in connector: Error creating a database connection.

It works for a bit then crashes.

**Comment by oxhey** [comment]
env key still exists.

running on a pi 3 model b

Think it might be the pi thats the issue. It seems to freeze / get to hot

**Comment by oxhey** [comment]
I get ./init-db.sh: line 6: NODE_ENV: unbound variable

**Comment by robhammond** [comment]
Ok sorry - try running the following from the same directory:

```sh
npx prisma generate
npx prisma migrate deploy
npx prisma db seed
```

**Comment by oxhey** [comment]
Thats better!

All the pages now work and its super fast switching between them.

I still get ./init-db.sh: line 6: NODE_ENV: unbound variable but I see no errors in the log so happy days!

**Comment by robhammond** [comment]
Oh did you try `pm2 reload` after running the above prisma commands?

You can try the below to fix that node_env issue:

```sh
echo "export NODE_ENV=production" >> ~/.bashrc
source ~/.bashrc
```

**Comment by oxhey** [comment]
I restarted the system. Seems to be working better now.
