### ISSUE TITLE
Cannot access any web page other than the main page.

### ISSUE THREAD

**Issue by kmarshallsay** [robhammond/home-analytics#4]
Hey Rob

Further to our email conversation the other week, i've done a complete reinstall to see if I can get it up and running.  however I am still encountering the same issue with (what I beleive) the seed.js file.

```sh
Running seed command `node prisma/seed.js` ...
PrismaClientInitializationError:
Invalid `prisma.entity.create()` invocation in
/var/www/home-analytics/app/web/prisma/seed.js:5:39

  2 const prisma = new PrismaClient();
  3
  4 async function main() {
→ 5     const n3rgy = await prisma.entity.create(
Error in connector: Error creating a database connection. (Error parsing connection string: /var/www/home-analytics/app/web/prisma/)
    at Rn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:7601)
    at Rn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6754)
    at /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3010
    at async /var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:3225
    at async t._executeRequest (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:177:11403)
    at async main (/var/www/home-analytics/app/web/prisma/seed.js:5:19) {
  clientVersion: '4.16.2',
  errorCode: undefined
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: node prisma/seed.js`

```

**Comment by robhammond** [comment]
Thanks for following up - are you able to drop in the output of a `printenv` command?

**Comment by kmarshallsay** [comment]
SHELL=/bin/bash
NO_AT_BRIDGE=1
PWD=/home/kmarshallsay
LOGNAME=kmarshallsay
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/kmarshallsay
LANG=en_GB.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.10.6 31831 192.168.10.59 22
XDG_SESSION_CLASS=user
TERM=xterm
USER=kmarshallsay
SHLVL=1
HA_DB_URL=/var/www/home-analytics/db/prod.db
XDG_SESSION_ID=10
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=192.168.10.6 31831 22
PATH=/home/kmarshallsay/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
SSH_TTY=/dev/pts/0
TEXTDOMAIN=Linux-PAM
_=/usr/bin/printenv

**Comment by robhammond** [comment]
Oh I think I see the issue; I think the HA_DB_URL path is wrong - try changing the path to this in your `~/.profile` file and then restarting the shell:

`HA_DB_URL=/var/www/home-analytics/app/db/prod.db`

**Comment by kmarshallsay** [comment]
sorry had to restart the Pi:

Environment variables loaded from .env
Running seed command `node prisma/seed.js` ...
PrismaClientKnownRequestError:
Invalid `prisma.entity.create()` invocation in
/var/www/home-analytics/app/web/prisma/seed.js:5:39

  2 const prisma = new PrismaClient();
  3
  4 async function main() {
→ 5     const n3rgy = await prisma.entity.create(
The table `main.Entity` does not exist in the current database.
    at Rn.handleRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/var/www/home-analytics/app/web/node_modules/@prisma/client/runtime/library.js:174:6344)
    at async main (/var/www/home-analytics/app/web/prisma/seed.js:5:19) {
  code: 'P2021',
  clientVersion: '4.16.2',
  meta: { table: 'main.Entity' }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: node prisma/seed.js

**Comment by kmarshallsay** [comment]
sorted now I think Rob, I had to re-rerun all the npx commands again.  btw it might be worth adding the ../app/... into the file path on the instructions - i just copied and pasted that part and didn't clock that it should have been pointing to that location.

I'll have a play now to see if I can access the webpages

**Comment by robhammond** [comment]
> sorted now I think Rob, I had to re-rerun all the npx commands again. btw it might be worth adding the ../app/... into the file path on the instructions - i just copied and pasted that part and didn't clock that it should have been pointing to that location.
> 
> I'll have a play now to see if I can access the webpages

Thanks yes I spotted that snafu on the readme and have fixed now thank you!

**Comment by kmarshallsay** [comment]
cool, I think we're cooking with gas now, if i encounter anymore issues I'll let you know.

**Comment by robhammond** [comment]
Great, thank you for your feedback
